serenity {
  project.name = "Reto Automatización DemoQA"
}

webdriver {
  driver = chrome
  base.url = "https://demoqa.com"

  # 👇 ESTA ES LA CLAVE
  chrome.driver = "C:/drivers/chromedriver.exe"
}

chrome {
  switches = "--start-maximized"
}